<?xml version="1.0" encoding="utf-8"?><Database Name="college-event" Class="CollegeEventDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=project.cxmh3tpmooew.us-east-1.rds.amazonaws.com,1433;Initial Catalog=college-event;Persist Security Info=True;User ID=master" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="college_eventConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="Eid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="eType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="eCategory" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="eDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="start" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="[end]" Member="end" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="contact" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="event_no" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="set_event_location_Event" Member="set_event_location" ThisKey="event_no" OtherKey="event_no" Type="set_event_location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.member_master_tbl" Member="member_master_tbls">
    <Type Name="member_master_tbl">
      <Column Name="uid" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.set_event_location" Member="set_event_locations">
    <Type Name="set_event_location">
      <Column Name="event_no" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="set_event_location_Event" Member="Events" ThisKey="event_no" OtherKey="event_no" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.university_profile" Member="university_profiles">
    <Type Name="university_profile">
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="number_of_students" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="university_img" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>